eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8082
spring:
  application:
    name: service-auth
  datasource:
    password: postgres
    url: jdbc:postgresql:wcp
    username: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
app:
  jwt:
    expiration: 900000
    header: Authorization
    header.prefix: 'Bearer '
    secret: mySecret
  cache:
    logoutToken:
      maxSize: 1000
  token:
    email:
      verification:
        duration: 3600000
    password:
      reset:
        duration: 3600000
    refresh:
      duration: 2592000000
  velocity:
    templates:
      location: /templates/
